# taken from https://packaging.python.org/tutorials/packaging-projects/

[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--full-trace -ra --durations=0 -v --ff -n 2"
testpaths = ["tests"]
