name: jimmy_runner

# Controls when the workflow will run
on:
  # run tests at 2h and 16h everyday.
  schedule:
    - cron: "0 2,16 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ self-hosted,cml,gpu ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          cache: 'pip'

      - name: Install pytest
        run: |
          pip install pytest
          pip install pytest-xdist

      - name: Run pytest
        run: pytest
